# Generated by Django 4.2.8 on 2024-04-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_telegram',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Телеграм ID'),
        ),
    ]
