# Generated by Django 4.2.8 on 2024-04-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телеграм ID'),
        ),
    ]
