# Generated by Django 4.2.8 on 2024-04-13 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='Место привычки')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Время привычки')),
                ('action', models.CharField(max_length=250, verbose_name='Действие привычки')),
                ('is_pleasant', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак приятной привычки')),
                ('frequency', models.PositiveSmallIntegerField(default=1, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.PositiveSmallIntegerField(blank=True, default=120, null=True, verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
