# Generated by Django 4.2.8 on 2024-04-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.PositiveIntegerField(default=120, verbose_name='время на выполнение, сек.'),
        ),
    ]
